alpha/alpha/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_profile/',include("my_profile.urls")),
    path('my_webpage/', include("my_webpage.urls"))
]

alpha/my_profile/urls.py
from django.urls import path

from . import views

app_name = "my_profile"
urlpatterns = [
    path("",views.index, name="index"),
    path("project", views.project, name="project"),
    path("add",views.add_project, name="add")
]

alpha/my_webpage/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("",views.index, name="index")
]

alpha/my_webpage/models.py
from django.db import models

# Create your models here.

alpha/my_profile/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from django import forms


class NewTaskForm(forms.Form):
    name = forms.CharField(label="New Project")
    desc = forms.CharField(label="Description")
    link = forms.CharField(label="Link")

    
projects = [
    {
        "name": "Morse Code:Encoder Decoder",
        "desc": "A program written in python that converts alphaneumeric characters into morse code\
              or convert morse code into alphanumeric characters",
        "link": "https://github.com/kyusyer/morsecode"
    },
    {
        "name": "Fullstack website using django",
        "desc": "A full stack website that contains my resume that is written in django",
        "link": "https://github.com/kyusyer/django_projecty2"
    }
]


# Create your views here.

def index(request):
    return render(request,"my_profile/index.html")

def project(request):
    return render(request, "my_profile/project.html", {
        "projects": projects
    })


def add_project(request): 
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            desc = form.cleaned_data["desc"]
            link = form.cleaned_data["link"]
            projects.append(
                {
                    "name": name,
                    "desc": desc,
                    "link": link
                }
            )
            return HttpResponseRedirect(reverse("my_profile:project"))

    return render(request, "my_profile/add_project.html", {"form": NewTaskForm()} )

alpha/my_webpage/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "my_webpage/index.html")

alpha/my_profile/templates/my_profile/add_project.html
{% extends "my_profile/header.html" %}

{% block content %}
<div id="add_div">
    <h1>Add project</h1>
    <form action="{% url 'my_profile:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="add project">
    </form>




</div>
{% endblock %}

alpha/my_profile/templates/my_profile/header.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="{% static 'my_profile/styling.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale=1.0" ,>
    <title>
        My Profile
    </title>
</head>

<body>
    <!-- header content-->
    <heading>
        <div id="header">
            <div id="home_link">
                <a href="{% url 'my_profile:index'%}">Home</a>
            </div>
            <div id=" project_link">
                <a href=" {% url 'my_profile:project' %}">Projects</a>
            </div>
        </div>
    </heading>
    <main>
        {% block content %}
        {% endblock %}
    </main>


</body>

</html>

alpha/my_profile/templates/my_profile/index.html
{% extends "my_profile/header.html" %}


    <!-- header part -->

    <!-- main content -->

    {% block content %}
    <div id="body_container">
    <div>
        <h1><b>ALVIN E. GARIN</b></h1>
        <h3>
            <tr>
                <td>Muntinlupa City |</td>
                <td>(+63)932-124-2045 |</td>
                <td>garinalvin.e@gmail.com |</td>
                <td><a href="www.linkedin.com/in/aegarin">www.linkedin.com/in/aegarin</a></td>
            </tr>
        </h3>
    </div>
    <hr>
    <div class="summary">
        <p>
            Dynamic engineer with 5+ years in manufacturing, specializing in data analysis and machine
            line support. Proficient in MS Excel, PowerPoint, Python, and SQL. Recognized for analytical
            prowess, organizational acumen, and attention to detail. Adept at driving operational efficiency
            and adapting to change. Proven track record of success in independent and collaborative
            settings, showcasing a highly trainable and detail-oriented approach.
        </p>
    </div>
    <hr>
    <div class="education">
        <h2>
            <em>EDUCATION</em>
        </h2>
        <table>
            <tr>
                <td><b>Bachelor of Science in Electronics Engineering |</b></td>
                <td><b>Colegio de Dagupan (Universidad de Dagupan)</b></td>
            </tr>
            <tr>
                <td><i>April 2017</i></td>
                <td></td>
            </tr>

        </table>
        <hr>
    </div>
    <div class="experience">
        <h2>
            <em>EXPERIENCE</em>
        </h2>
        <table>
            <tr>
                <td><b>PROBE TEST PRODUCT ENGINEER |ALLEGRO MICROSYSTEMS PHILIPPINES INC</b></td>
            </tr>
            <tr>
                <td><i>May 2020 - June 2023 (3 years and 2 months)</i></td>
            </tr>
            <tr>
                <td>
                    <ul>
                        <li>
                            Performed data gathering and data analyses of manufacturing data that enabled
                            focused solutions on issues affecting productions.
                        </li>
                        <li>
                            Generated daily, weekly and monthly reports that are used to identify line
                            performance issues and solutions.
                        </li>
                        <li>
                            Generated and reviewed gage report for new hardware and system spares that
                            enabled more resources for production processes.
                        </li>
                        <li>
                            Reviewed and updated process workflows ensuring new standard are properly
                            documented
                        </li>
                        <li>
                            Provided line sustaining support that helps met production targets
                        </li>
                        <li>
                            Checked program related and machine issues increasing machine compatibility.
                        </li>
                        <li>
                            Performed repairs of Eagle test system and TEL Prober
                        </li>
                        <li>
                            Troubleshooted product to machine compatibility test issues increasing testing
                        </li>
                    </ul>
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td><b>PROBE SUSTAINING TECHNICIAN |ALLEGRO MICROSYSTEMS PHILIPPINES INC</b></td>
            </tr>
            <tr>
                <td><i>Oct 2017 – May 2020 (2 years and 8 months)</i></td>
            </tr>
            <tr>
                <td>
                    <ul>
                        <li>
                            maintained machine in good running condition that helps production met the weekly
                            t target machine output and machine utilization
                        </li>
                        <li>
                            Analyzed and validated test data and rejects that ensured test result integrity
                        </li>
                        <li>
                            Coordinated with engineers to facilitate manufacturinfg decisions
                        </li>

                    </ul>
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td><b>APPRENTICE ENGINEER |AMKOR TECHNOLOGY PHILS. INC</b></td>
            </tr>
            <tr>
                <td><i>Feb 2017 – Jul 2017 (6 months)</i></td>
            </tr>
        </table>
    </div>
    <hr>
    <div class="skills">
        <h2 id="skills">
            <em>SKILLS</em>
        </h2>
        <table>
            <td>
                <ul>
                    <li>Data Analysis</li>
                    <li>Microsoft Excel/ Word/ PowerPoint</li>
                    <li>Microsoft PowerBI</li>
                    <li>C and Python Programming</li>
                    <li>PostgreSQL</li>
                    <li>Eagle Test System</li>
                    <li>
                        Galaxy/ Mentor Examinator
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>Hardworking</li>
                    <li>Detailed Oriented</li>
                    <li>Can work independently or as part of a team</li>
                    <li>Adaptable</li>
                    <li>Higly trainable</li>
                </ul>
            </td>
        </table>
    </div>
    <hr>
    <div class="certifications">
        <h2><em>CERTIFICATIONS</em></h2>
        <table>
            <tr>
                <td><b><u>Preparing Data for Analysis with Microsoft Excel | Microsoft through Coursera</u></b>
                </td>
            </tr>
            <tr>
                <td>
                    Dec. 2023
                </td>
            </tr>
            <tr>
                <td>
                    <p>
                        &ensp;Certificate of successful completion of Preparing Data for Analysis with Microsoft Excel
                    </p>
                    <p>
                        &ensp;Certificate link: <a
                            href="https://coursera.org/verify/3QATPQK7WUF3">https://coursera.org/verify/3QATPQK7WUF3</a>
                    </p>
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td><b><u>Technical Support Fundamentals | Google through Coursera</u></b>
                </td>
            </tr>
            <tr>
                <td>
                    Nov. 2023
                </td>
            </tr>
            <tr>
                <td>
                    <p>
                        &ensp;Certificate of successful completion of Technical Support fundamentals.
                    </p>
                    <p>
                        &ensp;Certificate link: <a
                            href="https://coursera.org/verify/R6YCFYJ658W">https://coursera.org/verify/R6YCFYJ658WP</a>
                    </p>
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td><b><u>CS50P - Introduction to Python Programming Course | Harvard University</u></b>
                </td>
            </tr>
            <tr>
                <td>
                    Oct. 2023
                </td>
            </tr>
            <tr>
                <td>
                    <p>
                        &ensp;Certification on completion of CS50's Introduction to Programming with Python, including
                        nine problem sets and one final project
                    </p>
                    <p>
                        &ensp;Certificate link: <a href="https://cs50.harvard.edu/certificates/5b3f6d3e-46d2-4ca4-a170-
                        5859ffea6d38">https://cs50.harvard.edu/certificates/5b3f6d3e-46d2-4ca4-a170-
                            5859ffea6d38</a>
                    </p>
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <td><b><u>Python (Basic) Programming| Hacker Rank</u></b>
                </td>
            </tr>
            <tr>
                <td>
                    Oct. 2023
                </td>
            </tr>
            <tr>
                <td>
                    <p>
                        &ensp;Certification of clearing the assessment for the skill Python (Basic)
                        Certification link:
                    </p>
                    <p>
                        &ensp;Certificate link: <a
                            href="https://www.hackerrank.com/certificates/9985072cd1c">https://www.hackerrank.com/certificates/9985072cd1c</a>
                    </p>
                </td>
            </tr>
        </table>
    </div>
    <hr>
    <div class="license">
        <h2>LICENSES:</h2>
        <table>
            <tr>
                <td><b><u>Electronics Engineer PHILIPPINE Professional Regulation Commission</u></b>
                </td>
            </tr>
            <tr>
                <td>
                    Dec. 2017
                </td>
            </tr>
            <tr>
                <td>
                    <p>
                        &ensp;License to practice as electronics engineer in the Philippines.
                    </p>
                </td>
            </tr>
        </table>

    </div>
</div>


{% endblock %}

alpha/my_profile/templates/my_profile/project.html
{% extends "my_profile/header.html" %}

{% block content %}
<div id="project_block">

    {% for project in projects %}
    <h3>{{ project.name }}</h3>
    <ul>
        <li>
            {{ project.desc }}
        </li>
        <br>
        <li>
            project link: <a href="{{ project.link }}" target="_blank">
                {{ project.link }}</a>

        </li>
    </ul>
    {% endfor %}
    <a href="{% url 'my_profile:add' %}">Add project</a>

</div>
{% endblock %}

alpha/my_webpage/templates/my_webpage/index.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <link rel="stylesheet" href={% static "my_webpage/style.css" %}>
    <meta name="viewport" content="initial-scale=1, width=device-width">
    <title>
        meta
    </title>
</head>

<body>

    <div class="welcome_sec">
        <h1 id="welcome_h1">
            Welcome to My Webpage
        </h1>
    </div>
    <div class="unknown_section">
        <h1>content here</h1>
    </div>
    <div class="sect3">
        
        <h1>Profile pic</h1> <div>
        <img s src={% static "my_webpage/files/profile pic.jpg" %} alt="pic" height="300">
        
    </div>
    </div>

    <div id="container">
        <div>box1</div>
        <div>box2</div>
        <div>box3</div>
        <div>box4</div>
    </div>
    <div class="div4">
        <iframe src={% static "my_webpage/files/video.html" %} frameborder="0" height="500" width="600"></iframe>

    </div>






</body>

</html>